### ISSUE TITLE
你好，请问这个在WIN7 32位系统下可以用么？

### ISSUE THREAD

**Issue by lki2019** [coolzilj/mama#2]
git clone git@github.com:coolzilj/mama.git
cd mama
node server.js

这3步在哪里输入呢？

小白求教 别见笑！

**Comment by coolzilj** [comment]
没有在 windows 测试过，具体要看
you-get
mpv
Node.js
Tampermonkey
这几个在 windows 能不能正常跑起来。

命令行在 cmd 输入
